#!/bin/bash
#
# start/stop Starman (Circos) Application Server

# chkconfig: 2345 99 00
# description: Starman (Circos) Application Server
# processname: starman

PERL_HOME=/usr/local/perl-5.16.3-centos6.4
export PERL_HOME

case "$1" in

'start')
    su - starman -c "cd /usr/local/starman/target-circos; $PERL_HOME/bin/perl bin/circos_server.pl -p 8180 -w 10 start"
    ;;
'stop')
    su - starman -c "cd /usr/local/starman/target-circos; $PERL_HOME/bin/perl bin/circos_server.pl -p 8180 stop"
    ;;
'status')
    su - starman -c "cd /usr/local/starman/target-circos; $PERL_HOME/bin/perl bin/circos_server.pl status"
    ;;
'restart')
    su - starman -c "cd /usr/local/starman/target-circos; $PERL_HOME/bin/perl bin/circos_server.pl -p 8180 -w 10 restart"
    ;;
*)
    echo "Usage: $0 { start | stop | status | restart }"
    ;;
esac
exit 0
